### PR TITLE
Add autofocus attribute to create workspace dialog

### PR DESCRIPTION
**Pull request by danlamanna**

### CODE REVIEW

**Comment by danlamanna** [comment]
I haven't actually tested this since I don't have a dev space up, but I hope the intent is clear. Clicking create workspace should let the user immediately start typing, instead of having to click the text dialog for focus.

**Comment by waxlamp** [comment]
This works like a charm. If you mark it ready for review I'll approve it. Thanks @danlamanna!

**Comment by JackWilb** [comment]
Only seems to work on chrome for me, not firefox. I also think we should expand this to the create table +  create graph dialogs too for completeness

**Comment by waxlamp** [comment]
The problem with Firefox seems to be something Vuetify is actively trying to fix. I agree about adding `autofocus` to the other dialogs, but let's do them in followup PRs since Dan's busy with other stuff today.

**Pull request merged**
