### PR TITLE
Add simple redirect on invalid workspaces

### LINKED ISSUE #240: Display new page or redirect if invalid workspace name entered
When navigating multinet, if you enter the url of a workspace that does not exist (or perhaps that you just deleted but still have in your browser url), it will display the page as if the workspace is just empty. This could be confusing and causes problems if the user then tries to add tables (as the requests fail). A solution to this would be to display a workspace not found page, but a more immediate solution would be to simply redirect to the home page, like is already done for catching incorrect URLs.

Screenshot from 2020-01-08 11-03-40

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Fixes #240. This is a simple redirect back to the home page. If it's thought that more needs to be done we can revise this.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
> Can you run the linter to see if it makes any changes? (I see missing semicolons, for instance.) If you go into the `client` directory and run `yarn lint`, that should do the trick.

My bad, I guess I still need to get vscode completely setup. I've fixed the issues.

**Comment by waxlamp** [comment]
The only remaining issue is the use of `router.push()` -- I just tested and it degrades the back button UX quite a bit. Since `push()` creates a new history entry, the back button now goes back to the bad URL, then immediately navigates to the home page. This essentially makes it impossible to go back to a known good state prior to the bad URL.

I believe `router.replace()` is more appropriate here. What do you think?

In the future, I think we should handle this case with a custom 404 view rather than simply redirecting to the home page. We've discussed this in #185, so let's keep an eye out for how we can upgrade to that approach in the future.

**Comment by AlmightyYakob** [comment]
> The only remaining issue is the use of `router.push()` -- I just tested and it degrades the back button UX quite a bit. Since `push()` creates a new history entry, the back button now goes back to the bad URL, then immediately navigates to the home page. This essentially makes it impossible to go back to a known good state prior to the bad URL.
> 
> I believe `router.replace()` is more appropriate here. What do you think?
> 
> In the future, I think we should handle this case with a custom 404 view rather than simply redirecting to the home page. We've discussed this in #185, so let's keep an eye out for how we can upgrade to that approach in the future.

Yes I see the issue, good catch. I'll fix that now

**Comment by AlmightyYakob** [comment]
I agree with the thought on a 404 page. When the time comes, it should be fairly easy to replace this redirection, as both here and in the routes page that redirect this, we can instead of pointing to the home page just point to the new 404 page.

**Pull request merged**
