### PR TITLE
Table detail cleanup

### LINKED ISSUE #152: The navigation bar hides the table name
When inspecting a table, the top nav bar interferes with the name of the table. The fix for this should be to remove the nav bar over the table inspection window in a similar way to how it is removed for the graph inspector.

### PR DESCRIPTION
**Pull request by jtomeck**
Closes #152.

### CODE REVIEW

**Comment by waxlamp** [comment]
Looks great!

I will work on fixing that routing issue (#125) so that the breadcrumb link back to the workspace works properly.

Is the "all tables" panel supposed to have content in it?

**Comment by jtomeck** [comment]
@waxlamp - Yes it is, I just don't know how to do it. Taking a stab at it, though. I only created this PR so @AlmightyYakob could help with #125, which I believe he's doing now.

**Comment by AlmightyYakob** [comment]
3ae7639 fixes #125

**Comment by waxlamp** [comment]
The tests are only failing because of some legacy Python scripts unrelated to this pull request so I'm going to go ahead and merge this.

**Pull request merged**
