### PR TITLE
Add basic testing infrastructure and initial test

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Note: This PR removes Tox. This is because it was hindering the use of Pipenv, and wasn't really providing much benefit to this project specifically.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
@waxlamp the tests are failing due to the `test/data/table2csv.py` file. Does this belong in scripts?

**Comment by waxlamp** [comment]
@AlmightyYakob, I fixed the docstring errors in `table2csv.py` but yeah that script and `PaulRevereAppD.csv` could possibly be placed elsewhere, but not in the scripts directory. For now let's just leave them where they are.

**Comment by waxlamp** [comment]
I experimented with splitting apart the compound assertions in the test module. Let me know if there's a good reason not to do that, and then we can revert that commit.

**Comment by AlmightyYakob** [comment]
> I experimented with splitting apart the compound assertions in the test module. Let me know if there's a good reason not to do that, and then we can revert that commit.

That's a good change, not really sure why I had it the original way tbh.

**Comment by AlmightyYakob** [comment]
> This looks great--could you just add something to the documentation to explain how to run the testing and coverage?

@waxlamp I've done that, lmk what you think

**Pull request merged**
